# Generated by Django 3.2.8 on 2021-10-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComunidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRegion', models.IntegerField(choices=[(1, 'Caribe'), (2, 'Andina'), (3, 'Pacifico'), (4, 'Orinoquina'), (5, 'Amazonia'), (6, 'Insular')])),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_prod', models.IntegerField(choices=[(1, 'tejido'), (2, 'ceramica'), (3, 'joyeria'), (4, 'Orfebreria'), (5, 'tallado')])),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('caracteristica', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='authAppComInd.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Produc_comun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produc_comun', to='authAppComInd.comunidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produc_comun', to='authAppComInd.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidad', to='authAppComInd.region'),
        ),
    ]
